// Code generated by ent, DO NOT EDIT.

package tokenwalletledger

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tokenwalletledger type in the database.
	Label = "token_wallet_ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldChannelNameSnapshot holds the string denoting the channel_name_snapshot field in the database.
	FieldChannelNameSnapshot = "channel_name_snapshot"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldAmountTokens holds the string denoting the amount_tokens field in the database.
	FieldAmountTokens = "amount_tokens"
	// FieldEffectiveTokensSnapshot holds the string denoting the effective_tokens_snapshot field in the database.
	FieldEffectiveTokensSnapshot = "effective_tokens_snapshot"
	// Table holds the table name of the tokenwalletledger in the database.
	Table = "token_wallet_ledgers"
)

// Columns holds all SQL columns for tokenwalletledger fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldRequestID,
	FieldUsageLogID,
	FieldChannelID,
	FieldChannelNameSnapshot,
	FieldKind,
	FieldAmountTokens,
	FieldEffectiveTokensSnapshot,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int) error
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(int) error
	// UsageLogIDValidator is a validator for the "usage_log_id" field. It is called by the builders before save.
	UsageLogIDValidator func(int) error
	// ChannelIDValidator is a validator for the "channel_id" field. It is called by the builders before save.
	ChannelIDValidator func(int) error
	// DefaultChannelNameSnapshot holds the default value on creation for the "channel_name_snapshot" field.
	DefaultChannelNameSnapshot string
	// AmountTokensValidator is a validator for the "amount_tokens" field. It is called by the builders before save.
	AmountTokensValidator func(int64) error
	// DefaultEffectiveTokensSnapshot holds the default value on creation for the "effective_tokens_snapshot" field.
	DefaultEffectiveTokensSnapshot int64
	// EffectiveTokensSnapshotValidator is a validator for the "effective_tokens_snapshot" field. It is called by the builders before save.
	EffectiveTokensSnapshotValidator func(int64) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindCredit Kind = "credit"
	KindDebit  Kind = "debit"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindCredit, KindDebit:
		return nil
	default:
		return fmt.Errorf("tokenwalletledger: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the TokenWalletLedger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByChannelNameSnapshot orders the results by the channel_name_snapshot field.
func ByChannelNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelNameSnapshot, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByAmountTokens orders the results by the amount_tokens field.
func ByAmountTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountTokens, opts...).ToFunc()
}

// ByEffectiveTokensSnapshot orders the results by the effective_tokens_snapshot field.
func ByEffectiveTokensSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveTokensSnapshot, opts...).ToFunc()
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Kind) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Kind) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Kind(str)
	if err := KindValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Kind", str)
	}
	return nil
}
