// Code generated by ent, DO NOT EDIT.

package tokenwalletledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldUserID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldRequestID, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldUsageLogID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldChannelID, v))
}

// ChannelNameSnapshot applies equality check predicate on the "channel_name_snapshot" field. It's identical to ChannelNameSnapshotEQ.
func ChannelNameSnapshot(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldChannelNameSnapshot, v))
}

// AmountTokens applies equality check predicate on the "amount_tokens" field. It's identical to AmountTokensEQ.
func AmountTokens(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldAmountTokens, v))
}

// EffectiveTokensSnapshot applies equality check predicate on the "effective_tokens_snapshot" field. It's identical to EffectiveTokensSnapshotEQ.
func EffectiveTokensSnapshot(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldEffectiveTokensSnapshot, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldUserID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldRequestID, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotNull(FieldUsageLogID))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotNull(FieldChannelID))
}

// ChannelNameSnapshotEQ applies the EQ predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotEQ(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotNEQ applies the NEQ predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotNEQ(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotIn applies the In predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotIn(vs ...string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldChannelNameSnapshot, vs...))
}

// ChannelNameSnapshotNotIn applies the NotIn predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotNotIn(vs ...string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldChannelNameSnapshot, vs...))
}

// ChannelNameSnapshotGT applies the GT predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotGT(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotGTE applies the GTE predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotGTE(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotLT applies the LT predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotLT(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotLTE applies the LTE predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotLTE(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotContains applies the Contains predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotContains(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldContains(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotHasPrefix applies the HasPrefix predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotHasPrefix(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldHasPrefix(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotHasSuffix applies the HasSuffix predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotHasSuffix(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldHasSuffix(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotEqualFold applies the EqualFold predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotEqualFold(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEqualFold(FieldChannelNameSnapshot, v))
}

// ChannelNameSnapshotContainsFold applies the ContainsFold predicate on the "channel_name_snapshot" field.
func ChannelNameSnapshotContainsFold(v string) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldContainsFold(FieldChannelNameSnapshot, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldKind, vs...))
}

// AmountTokensEQ applies the EQ predicate on the "amount_tokens" field.
func AmountTokensEQ(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldAmountTokens, v))
}

// AmountTokensNEQ applies the NEQ predicate on the "amount_tokens" field.
func AmountTokensNEQ(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldAmountTokens, v))
}

// AmountTokensIn applies the In predicate on the "amount_tokens" field.
func AmountTokensIn(vs ...int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldAmountTokens, vs...))
}

// AmountTokensNotIn applies the NotIn predicate on the "amount_tokens" field.
func AmountTokensNotIn(vs ...int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldAmountTokens, vs...))
}

// AmountTokensGT applies the GT predicate on the "amount_tokens" field.
func AmountTokensGT(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldAmountTokens, v))
}

// AmountTokensGTE applies the GTE predicate on the "amount_tokens" field.
func AmountTokensGTE(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldAmountTokens, v))
}

// AmountTokensLT applies the LT predicate on the "amount_tokens" field.
func AmountTokensLT(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldAmountTokens, v))
}

// AmountTokensLTE applies the LTE predicate on the "amount_tokens" field.
func AmountTokensLTE(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldAmountTokens, v))
}

// EffectiveTokensSnapshotEQ applies the EQ predicate on the "effective_tokens_snapshot" field.
func EffectiveTokensSnapshotEQ(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldEQ(FieldEffectiveTokensSnapshot, v))
}

// EffectiveTokensSnapshotNEQ applies the NEQ predicate on the "effective_tokens_snapshot" field.
func EffectiveTokensSnapshotNEQ(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNEQ(FieldEffectiveTokensSnapshot, v))
}

// EffectiveTokensSnapshotIn applies the In predicate on the "effective_tokens_snapshot" field.
func EffectiveTokensSnapshotIn(vs ...int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldIn(FieldEffectiveTokensSnapshot, vs...))
}

// EffectiveTokensSnapshotNotIn applies the NotIn predicate on the "effective_tokens_snapshot" field.
func EffectiveTokensSnapshotNotIn(vs ...int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldNotIn(FieldEffectiveTokensSnapshot, vs...))
}

// EffectiveTokensSnapshotGT applies the GT predicate on the "effective_tokens_snapshot" field.
func EffectiveTokensSnapshotGT(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGT(FieldEffectiveTokensSnapshot, v))
}

// EffectiveTokensSnapshotGTE applies the GTE predicate on the "effective_tokens_snapshot" field.
func EffectiveTokensSnapshotGTE(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldGTE(FieldEffectiveTokensSnapshot, v))
}

// EffectiveTokensSnapshotLT applies the LT predicate on the "effective_tokens_snapshot" field.
func EffectiveTokensSnapshotLT(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLT(FieldEffectiveTokensSnapshot, v))
}

// EffectiveTokensSnapshotLTE applies the LTE predicate on the "effective_tokens_snapshot" field.
func EffectiveTokensSnapshotLTE(v int64) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.FieldLTE(FieldEffectiveTokensSnapshot, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TokenWalletLedger) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TokenWalletLedger) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TokenWalletLedger) predicate.TokenWalletLedger {
	return predicate.TokenWalletLedger(sql.NotPredicates(p))
}
