// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/emailverificationchallenge"
)

// EmailVerificationChallenge is the model entity for the EmailVerificationChallenge schema.
type EmailVerificationChallenge struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// CodeDigest holds the value of the "code_digest" field.
	CodeDigest string `json:"-"`
	// SourceHash holds the value of the "source_hash" field.
	SourceHash string `json:"-"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt   *time.Time `json:"consumed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailVerificationChallenge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailverificationchallenge.FieldID, emailverificationchallenge.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case emailverificationchallenge.FieldEmail, emailverificationchallenge.FieldCodeDigest, emailverificationchallenge.FieldSourceHash:
			values[i] = new(sql.NullString)
		case emailverificationchallenge.FieldCreatedAt, emailverificationchallenge.FieldUpdatedAt, emailverificationchallenge.FieldExpiresAt, emailverificationchallenge.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailVerificationChallenge fields.
func (_m *EmailVerificationChallenge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailverificationchallenge.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case emailverificationchallenge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case emailverificationchallenge.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case emailverificationchallenge.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case emailverificationchallenge.FieldCodeDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_digest", values[i])
			} else if value.Valid {
				_m.CodeDigest = value.String
			}
		case emailverificationchallenge.FieldSourceHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_hash", values[i])
			} else if value.Valid {
				_m.SourceHash = value.String
			}
		case emailverificationchallenge.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case emailverificationchallenge.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case emailverificationchallenge.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailVerificationChallenge.
// This includes values selected through modifiers, order, etc.
func (_m *EmailVerificationChallenge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this EmailVerificationChallenge.
// Note that you need to call EmailVerificationChallenge.Unwrap() before calling this method if this EmailVerificationChallenge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmailVerificationChallenge) Update() *EmailVerificationChallengeUpdateOne {
	return NewEmailVerificationChallengeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmailVerificationChallenge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmailVerificationChallenge) Unwrap() *EmailVerificationChallenge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmailVerificationChallenge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmailVerificationChallenge) String() string {
	var builder strings.Builder
	builder.WriteString("EmailVerificationChallenge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("code_digest=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("source_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// EmailVerificationChallenges is a parsable slice of EmailVerificationChallenge.
type EmailVerificationChallenges []*EmailVerificationChallenge
