// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/emailverificationchallenge"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// EmailVerificationChallengeUpdate is the builder for updating EmailVerificationChallenge entities.
type EmailVerificationChallengeUpdate struct {
	config
	hooks     []Hook
	mutation  *EmailVerificationChallengeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the EmailVerificationChallengeUpdate builder.
func (_u *EmailVerificationChallengeUpdate) Where(ps ...predicate.EmailVerificationChallenge) *EmailVerificationChallengeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailVerificationChallengeUpdate) SetUpdatedAt(v time.Time) *EmailVerificationChallengeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmailVerificationChallengeUpdate) SetEmail(v string) *EmailVerificationChallengeUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdate) SetNillableEmail(v *string) *EmailVerificationChallengeUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCodeDigest sets the "code_digest" field.
func (_u *EmailVerificationChallengeUpdate) SetCodeDigest(v string) *EmailVerificationChallengeUpdate {
	_u.mutation.SetCodeDigest(v)
	return _u
}

// SetNillableCodeDigest sets the "code_digest" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdate) SetNillableCodeDigest(v *string) *EmailVerificationChallengeUpdate {
	if v != nil {
		_u.SetCodeDigest(*v)
	}
	return _u
}

// SetSourceHash sets the "source_hash" field.
func (_u *EmailVerificationChallengeUpdate) SetSourceHash(v string) *EmailVerificationChallengeUpdate {
	_u.mutation.SetSourceHash(v)
	return _u
}

// SetNillableSourceHash sets the "source_hash" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdate) SetNillableSourceHash(v *string) *EmailVerificationChallengeUpdate {
	if v != nil {
		_u.SetSourceHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EmailVerificationChallengeUpdate) SetExpiresAt(v time.Time) *EmailVerificationChallengeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdate) SetNillableExpiresAt(v *time.Time) *EmailVerificationChallengeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EmailVerificationChallengeUpdate) SetAttempts(v int) *EmailVerificationChallengeUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdate) SetNillableAttempts(v *int) *EmailVerificationChallengeUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EmailVerificationChallengeUpdate) AddAttempts(v int) *EmailVerificationChallengeUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *EmailVerificationChallengeUpdate) SetConsumedAt(v time.Time) *EmailVerificationChallengeUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdate) SetNillableConsumedAt(v *time.Time) *EmailVerificationChallengeUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *EmailVerificationChallengeUpdate) ClearConsumedAt() *EmailVerificationChallengeUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the EmailVerificationChallengeMutation object of the builder.
func (_u *EmailVerificationChallengeUpdate) Mutation() *EmailVerificationChallengeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailVerificationChallengeUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailVerificationChallengeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailVerificationChallengeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailVerificationChallengeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailVerificationChallengeUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if emailverificationchallenge.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized emailverificationchallenge.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := emailverificationchallenge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailVerificationChallengeUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := emailverificationchallenge.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeDigest(); ok {
		if err := emailverificationchallenge.CodeDigestValidator(v); err != nil {
			return &ValidationError{Name: "code_digest", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.code_digest": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceHash(); ok {
		if err := emailverificationchallenge.SourceHashValidator(v); err != nil {
			return &ValidationError{Name: "source_hash", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.source_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempts(); ok {
		if err := emailverificationchallenge.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.attempts": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EmailVerificationChallengeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EmailVerificationChallengeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EmailVerificationChallengeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailverificationchallenge.Table, emailverificationchallenge.Columns, sqlgraph.NewFieldSpec(emailverificationchallenge.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailverificationchallenge.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeDigest(); ok {
		_spec.SetField(emailverificationchallenge.FieldCodeDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceHash(); ok {
		_spec.SetField(emailverificationchallenge.FieldSourceHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(emailverificationchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(emailverificationchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(emailverificationchallenge.FieldConsumedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailverificationchallenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailVerificationChallengeUpdateOne is the builder for updating a single EmailVerificationChallenge entity.
type EmailVerificationChallengeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *EmailVerificationChallengeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailVerificationChallengeUpdateOne) SetUpdatedAt(v time.Time) *EmailVerificationChallengeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmailVerificationChallengeUpdateOne) SetEmail(v string) *EmailVerificationChallengeUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdateOne) SetNillableEmail(v *string) *EmailVerificationChallengeUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCodeDigest sets the "code_digest" field.
func (_u *EmailVerificationChallengeUpdateOne) SetCodeDigest(v string) *EmailVerificationChallengeUpdateOne {
	_u.mutation.SetCodeDigest(v)
	return _u
}

// SetNillableCodeDigest sets the "code_digest" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdateOne) SetNillableCodeDigest(v *string) *EmailVerificationChallengeUpdateOne {
	if v != nil {
		_u.SetCodeDigest(*v)
	}
	return _u
}

// SetSourceHash sets the "source_hash" field.
func (_u *EmailVerificationChallengeUpdateOne) SetSourceHash(v string) *EmailVerificationChallengeUpdateOne {
	_u.mutation.SetSourceHash(v)
	return _u
}

// SetNillableSourceHash sets the "source_hash" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdateOne) SetNillableSourceHash(v *string) *EmailVerificationChallengeUpdateOne {
	if v != nil {
		_u.SetSourceHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EmailVerificationChallengeUpdateOne) SetExpiresAt(v time.Time) *EmailVerificationChallengeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdateOne) SetNillableExpiresAt(v *time.Time) *EmailVerificationChallengeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EmailVerificationChallengeUpdateOne) SetAttempts(v int) *EmailVerificationChallengeUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdateOne) SetNillableAttempts(v *int) *EmailVerificationChallengeUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EmailVerificationChallengeUpdateOne) AddAttempts(v int) *EmailVerificationChallengeUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *EmailVerificationChallengeUpdateOne) SetConsumedAt(v time.Time) *EmailVerificationChallengeUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *EmailVerificationChallengeUpdateOne) SetNillableConsumedAt(v *time.Time) *EmailVerificationChallengeUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *EmailVerificationChallengeUpdateOne) ClearConsumedAt() *EmailVerificationChallengeUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the EmailVerificationChallengeMutation object of the builder.
func (_u *EmailVerificationChallengeUpdateOne) Mutation() *EmailVerificationChallengeMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailVerificationChallengeUpdate builder.
func (_u *EmailVerificationChallengeUpdateOne) Where(ps ...predicate.EmailVerificationChallenge) *EmailVerificationChallengeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailVerificationChallengeUpdateOne) Select(field string, fields ...string) *EmailVerificationChallengeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailVerificationChallenge entity.
func (_u *EmailVerificationChallengeUpdateOne) Save(ctx context.Context) (*EmailVerificationChallenge, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailVerificationChallengeUpdateOne) SaveX(ctx context.Context) *EmailVerificationChallenge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailVerificationChallengeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailVerificationChallengeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailVerificationChallengeUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if emailverificationchallenge.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized emailverificationchallenge.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := emailverificationchallenge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailVerificationChallengeUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := emailverificationchallenge.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeDigest(); ok {
		if err := emailverificationchallenge.CodeDigestValidator(v); err != nil {
			return &ValidationError{Name: "code_digest", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.code_digest": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceHash(); ok {
		if err := emailverificationchallenge.SourceHashValidator(v); err != nil {
			return &ValidationError{Name: "source_hash", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.source_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempts(); ok {
		if err := emailverificationchallenge.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.attempts": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EmailVerificationChallengeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EmailVerificationChallengeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EmailVerificationChallengeUpdateOne) sqlSave(ctx context.Context) (_node *EmailVerificationChallenge, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailverificationchallenge.Table, emailverificationchallenge.Columns, sqlgraph.NewFieldSpec(emailverificationchallenge.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailVerificationChallenge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailverificationchallenge.FieldID)
		for _, f := range fields {
			if !emailverificationchallenge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailverificationchallenge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailverificationchallenge.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeDigest(); ok {
		_spec.SetField(emailverificationchallenge.FieldCodeDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceHash(); ok {
		_spec.SetField(emailverificationchallenge.FieldSourceHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(emailverificationchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(emailverificationchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(emailverificationchallenge.FieldConsumedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &EmailVerificationChallenge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailverificationchallenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
