// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/emailverificationchallenge"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// EmailVerificationChallengeDelete is the builder for deleting a EmailVerificationChallenge entity.
type EmailVerificationChallengeDelete struct {
	config
	hooks    []Hook
	mutation *EmailVerificationChallengeMutation
}

// Where appends a list predicates to the EmailVerificationChallengeDelete builder.
func (_d *EmailVerificationChallengeDelete) Where(ps ...predicate.EmailVerificationChallenge) *EmailVerificationChallengeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EmailVerificationChallengeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EmailVerificationChallengeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EmailVerificationChallengeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(emailverificationchallenge.Table, sqlgraph.NewFieldSpec(emailverificationchallenge.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EmailVerificationChallengeDeleteOne is the builder for deleting a single EmailVerificationChallenge entity.
type EmailVerificationChallengeDeleteOne struct {
	_d *EmailVerificationChallengeDelete
}

// Where appends a list predicates to the EmailVerificationChallengeDelete builder.
func (_d *EmailVerificationChallengeDeleteOne) Where(ps ...predicate.EmailVerificationChallenge) *EmailVerificationChallengeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EmailVerificationChallengeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{emailverificationchallenge.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EmailVerificationChallengeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
