// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/emailverificationchallenge"
)

// EmailVerificationChallengeCreate is the builder for creating a EmailVerificationChallenge entity.
type EmailVerificationChallengeCreate struct {
	config
	mutation *EmailVerificationChallengeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailVerificationChallengeCreate) SetCreatedAt(v time.Time) *EmailVerificationChallengeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailVerificationChallengeCreate) SetNillableCreatedAt(v *time.Time) *EmailVerificationChallengeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailVerificationChallengeCreate) SetUpdatedAt(v time.Time) *EmailVerificationChallengeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmailVerificationChallengeCreate) SetNillableUpdatedAt(v *time.Time) *EmailVerificationChallengeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *EmailVerificationChallengeCreate) SetEmail(v string) *EmailVerificationChallengeCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetCodeDigest sets the "code_digest" field.
func (_c *EmailVerificationChallengeCreate) SetCodeDigest(v string) *EmailVerificationChallengeCreate {
	_c.mutation.SetCodeDigest(v)
	return _c
}

// SetSourceHash sets the "source_hash" field.
func (_c *EmailVerificationChallengeCreate) SetSourceHash(v string) *EmailVerificationChallengeCreate {
	_c.mutation.SetSourceHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EmailVerificationChallengeCreate) SetExpiresAt(v time.Time) *EmailVerificationChallengeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *EmailVerificationChallengeCreate) SetAttempts(v int) *EmailVerificationChallengeCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *EmailVerificationChallengeCreate) SetNillableAttempts(v *int) *EmailVerificationChallengeCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *EmailVerificationChallengeCreate) SetConsumedAt(v time.Time) *EmailVerificationChallengeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *EmailVerificationChallengeCreate) SetNillableConsumedAt(v *time.Time) *EmailVerificationChallengeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// Mutation returns the EmailVerificationChallengeMutation object of the builder.
func (_c *EmailVerificationChallengeCreate) Mutation() *EmailVerificationChallengeMutation {
	return _c.mutation
}

// Save creates the EmailVerificationChallenge in the database.
func (_c *EmailVerificationChallengeCreate) Save(ctx context.Context) (*EmailVerificationChallenge, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailVerificationChallengeCreate) SaveX(ctx context.Context) *EmailVerificationChallenge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailVerificationChallengeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailVerificationChallengeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailVerificationChallengeCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if emailverificationchallenge.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized emailverificationchallenge.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := emailverificationchallenge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if emailverificationchallenge.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized emailverificationchallenge.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := emailverificationchallenge.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := emailverificationchallenge.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailVerificationChallengeCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "EmailVerificationChallenge.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := emailverificationchallenge.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeDigest(); !ok {
		return &ValidationError{Name: "code_digest", err: errors.New(`ent: missing required field "EmailVerificationChallenge.code_digest"`)}
	}
	if v, ok := _c.mutation.CodeDigest(); ok {
		if err := emailverificationchallenge.CodeDigestValidator(v); err != nil {
			return &ValidationError{Name: "code_digest", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.code_digest": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceHash(); !ok {
		return &ValidationError{Name: "source_hash", err: errors.New(`ent: missing required field "EmailVerificationChallenge.source_hash"`)}
	}
	if v, ok := _c.mutation.SourceHash(); ok {
		if err := emailverificationchallenge.SourceHashValidator(v); err != nil {
			return &ValidationError{Name: "source_hash", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.source_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "EmailVerificationChallenge.expires_at"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "EmailVerificationChallenge.attempts"`)}
	}
	if v, ok := _c.mutation.Attempts(); ok {
		if err := emailverificationchallenge.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "EmailVerificationChallenge.attempts": %w`, err)}
		}
	}
	return nil
}

func (_c *EmailVerificationChallengeCreate) sqlSave(ctx context.Context) (*EmailVerificationChallenge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailVerificationChallengeCreate) createSpec() (*EmailVerificationChallenge, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailVerificationChallenge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailverificationchallenge.Table, sqlgraph.NewFieldSpec(emailverificationchallenge.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(emailverificationchallenge.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.CodeDigest(); ok {
		_spec.SetField(emailverificationchallenge.FieldCodeDigest, field.TypeString, value)
		_node.CodeDigest = value
	}
	if value, ok := _c.mutation.SourceHash(); ok {
		_spec.SetField(emailverificationchallenge.FieldSourceHash, field.TypeString, value)
		_node.SourceHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(emailverificationchallenge.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(emailverificationchallenge.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailVerificationChallenge.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailVerificationChallengeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailVerificationChallengeCreate) OnConflict(opts ...sql.ConflictOption) *EmailVerificationChallengeUpsertOne {
	_c.conflict = opts
	return &EmailVerificationChallengeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailVerificationChallenge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailVerificationChallengeCreate) OnConflictColumns(columns ...string) *EmailVerificationChallengeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailVerificationChallengeUpsertOne{
		create: _c,
	}
}

type (
	// EmailVerificationChallengeUpsertOne is the builder for "upsert"-ing
	//  one EmailVerificationChallenge node.
	EmailVerificationChallengeUpsertOne struct {
		create *EmailVerificationChallengeCreate
	}

	// EmailVerificationChallengeUpsert is the "OnConflict" setter.
	EmailVerificationChallengeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailVerificationChallengeUpsert) SetUpdatedAt(v time.Time) *EmailVerificationChallengeUpsert {
	u.Set(emailverificationchallenge.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsert) UpdateUpdatedAt() *EmailVerificationChallengeUpsert {
	u.SetExcluded(emailverificationchallenge.FieldUpdatedAt)
	return u
}

// SetEmail sets the "email" field.
func (u *EmailVerificationChallengeUpsert) SetEmail(v string) *EmailVerificationChallengeUpsert {
	u.Set(emailverificationchallenge.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsert) UpdateEmail() *EmailVerificationChallengeUpsert {
	u.SetExcluded(emailverificationchallenge.FieldEmail)
	return u
}

// SetCodeDigest sets the "code_digest" field.
func (u *EmailVerificationChallengeUpsert) SetCodeDigest(v string) *EmailVerificationChallengeUpsert {
	u.Set(emailverificationchallenge.FieldCodeDigest, v)
	return u
}

// UpdateCodeDigest sets the "code_digest" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsert) UpdateCodeDigest() *EmailVerificationChallengeUpsert {
	u.SetExcluded(emailverificationchallenge.FieldCodeDigest)
	return u
}

// SetSourceHash sets the "source_hash" field.
func (u *EmailVerificationChallengeUpsert) SetSourceHash(v string) *EmailVerificationChallengeUpsert {
	u.Set(emailverificationchallenge.FieldSourceHash, v)
	return u
}

// UpdateSourceHash sets the "source_hash" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsert) UpdateSourceHash() *EmailVerificationChallengeUpsert {
	u.SetExcluded(emailverificationchallenge.FieldSourceHash)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailVerificationChallengeUpsert) SetExpiresAt(v time.Time) *EmailVerificationChallengeUpsert {
	u.Set(emailverificationchallenge.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsert) UpdateExpiresAt() *EmailVerificationChallengeUpsert {
	u.SetExcluded(emailverificationchallenge.FieldExpiresAt)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *EmailVerificationChallengeUpsert) SetAttempts(v int) *EmailVerificationChallengeUpsert {
	u.Set(emailverificationchallenge.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsert) UpdateAttempts() *EmailVerificationChallengeUpsert {
	u.SetExcluded(emailverificationchallenge.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *EmailVerificationChallengeUpsert) AddAttempts(v int) *EmailVerificationChallengeUpsert {
	u.Add(emailverificationchallenge.FieldAttempts, v)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailVerificationChallengeUpsert) SetConsumedAt(v time.Time) *EmailVerificationChallengeUpsert {
	u.Set(emailverificationchallenge.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsert) UpdateConsumedAt() *EmailVerificationChallengeUpsert {
	u.SetExcluded(emailverificationchallenge.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailVerificationChallengeUpsert) ClearConsumedAt() *EmailVerificationChallengeUpsert {
	u.SetNull(emailverificationchallenge.FieldConsumedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EmailVerificationChallenge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmailVerificationChallengeUpsertOne) UpdateNewValues() *EmailVerificationChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(emailverificationchallenge.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailVerificationChallenge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailVerificationChallengeUpsertOne) Ignore() *EmailVerificationChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailVerificationChallengeUpsertOne) DoNothing() *EmailVerificationChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailVerificationChallengeCreate.OnConflict
// documentation for more info.
func (u *EmailVerificationChallengeUpsertOne) Update(set func(*EmailVerificationChallengeUpsert)) *EmailVerificationChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailVerificationChallengeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailVerificationChallengeUpsertOne) SetUpdatedAt(v time.Time) *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertOne) UpdateUpdatedAt() *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmail sets the "email" field.
func (u *EmailVerificationChallengeUpsertOne) SetEmail(v string) *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertOne) UpdateEmail() *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateEmail()
	})
}

// SetCodeDigest sets the "code_digest" field.
func (u *EmailVerificationChallengeUpsertOne) SetCodeDigest(v string) *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetCodeDigest(v)
	})
}

// UpdateCodeDigest sets the "code_digest" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertOne) UpdateCodeDigest() *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateCodeDigest()
	})
}

// SetSourceHash sets the "source_hash" field.
func (u *EmailVerificationChallengeUpsertOne) SetSourceHash(v string) *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetSourceHash(v)
	})
}

// UpdateSourceHash sets the "source_hash" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertOne) UpdateSourceHash() *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateSourceHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailVerificationChallengeUpsertOne) SetExpiresAt(v time.Time) *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertOne) UpdateExpiresAt() *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAttempts sets the "attempts" field.
func (u *EmailVerificationChallengeUpsertOne) SetAttempts(v int) *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *EmailVerificationChallengeUpsertOne) AddAttempts(v int) *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertOne) UpdateAttempts() *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateAttempts()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailVerificationChallengeUpsertOne) SetConsumedAt(v time.Time) *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertOne) UpdateConsumedAt() *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailVerificationChallengeUpsertOne) ClearConsumedAt() *EmailVerificationChallengeUpsertOne {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *EmailVerificationChallengeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailVerificationChallengeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailVerificationChallengeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailVerificationChallengeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailVerificationChallengeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailVerificationChallengeCreateBulk is the builder for creating many EmailVerificationChallenge entities in bulk.
type EmailVerificationChallengeCreateBulk struct {
	config
	err      error
	builders []*EmailVerificationChallengeCreate
	conflict []sql.ConflictOption
}

// Save creates the EmailVerificationChallenge entities in the database.
func (_c *EmailVerificationChallengeCreateBulk) Save(ctx context.Context) ([]*EmailVerificationChallenge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailVerificationChallenge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailVerificationChallengeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailVerificationChallengeCreateBulk) SaveX(ctx context.Context) []*EmailVerificationChallenge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailVerificationChallengeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailVerificationChallengeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailVerificationChallenge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailVerificationChallengeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailVerificationChallengeCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailVerificationChallengeUpsertBulk {
	_c.conflict = opts
	return &EmailVerificationChallengeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailVerificationChallenge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailVerificationChallengeCreateBulk) OnConflictColumns(columns ...string) *EmailVerificationChallengeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailVerificationChallengeUpsertBulk{
		create: _c,
	}
}

// EmailVerificationChallengeUpsertBulk is the builder for "upsert"-ing
// a bulk of EmailVerificationChallenge nodes.
type EmailVerificationChallengeUpsertBulk struct {
	create *EmailVerificationChallengeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmailVerificationChallenge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EmailVerificationChallengeUpsertBulk) UpdateNewValues() *EmailVerificationChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(emailverificationchallenge.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailVerificationChallenge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailVerificationChallengeUpsertBulk) Ignore() *EmailVerificationChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailVerificationChallengeUpsertBulk) DoNothing() *EmailVerificationChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailVerificationChallengeCreateBulk.OnConflict
// documentation for more info.
func (u *EmailVerificationChallengeUpsertBulk) Update(set func(*EmailVerificationChallengeUpsert)) *EmailVerificationChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailVerificationChallengeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailVerificationChallengeUpsertBulk) SetUpdatedAt(v time.Time) *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertBulk) UpdateUpdatedAt() *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmail sets the "email" field.
func (u *EmailVerificationChallengeUpsertBulk) SetEmail(v string) *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertBulk) UpdateEmail() *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateEmail()
	})
}

// SetCodeDigest sets the "code_digest" field.
func (u *EmailVerificationChallengeUpsertBulk) SetCodeDigest(v string) *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetCodeDigest(v)
	})
}

// UpdateCodeDigest sets the "code_digest" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertBulk) UpdateCodeDigest() *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateCodeDigest()
	})
}

// SetSourceHash sets the "source_hash" field.
func (u *EmailVerificationChallengeUpsertBulk) SetSourceHash(v string) *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetSourceHash(v)
	})
}

// UpdateSourceHash sets the "source_hash" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertBulk) UpdateSourceHash() *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateSourceHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EmailVerificationChallengeUpsertBulk) SetExpiresAt(v time.Time) *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertBulk) UpdateExpiresAt() *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAttempts sets the "attempts" field.
func (u *EmailVerificationChallengeUpsertBulk) SetAttempts(v int) *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *EmailVerificationChallengeUpsertBulk) AddAttempts(v int) *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertBulk) UpdateAttempts() *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateAttempts()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *EmailVerificationChallengeUpsertBulk) SetConsumedAt(v time.Time) *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *EmailVerificationChallengeUpsertBulk) UpdateConsumedAt() *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *EmailVerificationChallengeUpsertBulk) ClearConsumedAt() *EmailVerificationChallengeUpsertBulk {
	return u.Update(func(s *EmailVerificationChallengeUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *EmailVerificationChallengeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailVerificationChallengeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailVerificationChallengeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailVerificationChallengeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
