// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/tokenwalletledger"
)

// TokenWalletLedgerCreate is the builder for creating a TokenWalletLedger entity.
type TokenWalletLedgerCreate struct {
	config
	mutation *TokenWalletLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TokenWalletLedgerCreate) SetCreatedAt(v time.Time) *TokenWalletLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TokenWalletLedgerCreate) SetNillableCreatedAt(v *time.Time) *TokenWalletLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TokenWalletLedgerCreate) SetUpdatedAt(v time.Time) *TokenWalletLedgerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TokenWalletLedgerCreate) SetNillableUpdatedAt(v *time.Time) *TokenWalletLedgerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TokenWalletLedgerCreate) SetUserID(v int) *TokenWalletLedgerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *TokenWalletLedgerCreate) SetRequestID(v int) *TokenWalletLedgerCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *TokenWalletLedgerCreate) SetUsageLogID(v int) *TokenWalletLedgerCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *TokenWalletLedgerCreate) SetNillableUsageLogID(v *int) *TokenWalletLedgerCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *TokenWalletLedgerCreate) SetChannelID(v int) *TokenWalletLedgerCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_c *TokenWalletLedgerCreate) SetNillableChannelID(v *int) *TokenWalletLedgerCreate {
	if v != nil {
		_c.SetChannelID(*v)
	}
	return _c
}

// SetChannelNameSnapshot sets the "channel_name_snapshot" field.
func (_c *TokenWalletLedgerCreate) SetChannelNameSnapshot(v string) *TokenWalletLedgerCreate {
	_c.mutation.SetChannelNameSnapshot(v)
	return _c
}

// SetNillableChannelNameSnapshot sets the "channel_name_snapshot" field if the given value is not nil.
func (_c *TokenWalletLedgerCreate) SetNillableChannelNameSnapshot(v *string) *TokenWalletLedgerCreate {
	if v != nil {
		_c.SetChannelNameSnapshot(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *TokenWalletLedgerCreate) SetKind(v tokenwalletledger.Kind) *TokenWalletLedgerCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetAmountTokens sets the "amount_tokens" field.
func (_c *TokenWalletLedgerCreate) SetAmountTokens(v int64) *TokenWalletLedgerCreate {
	_c.mutation.SetAmountTokens(v)
	return _c
}

// SetEffectiveTokensSnapshot sets the "effective_tokens_snapshot" field.
func (_c *TokenWalletLedgerCreate) SetEffectiveTokensSnapshot(v int64) *TokenWalletLedgerCreate {
	_c.mutation.SetEffectiveTokensSnapshot(v)
	return _c
}

// SetNillableEffectiveTokensSnapshot sets the "effective_tokens_snapshot" field if the given value is not nil.
func (_c *TokenWalletLedgerCreate) SetNillableEffectiveTokensSnapshot(v *int64) *TokenWalletLedgerCreate {
	if v != nil {
		_c.SetEffectiveTokensSnapshot(*v)
	}
	return _c
}

// Mutation returns the TokenWalletLedgerMutation object of the builder.
func (_c *TokenWalletLedgerCreate) Mutation() *TokenWalletLedgerMutation {
	return _c.mutation
}

// Save creates the TokenWalletLedger in the database.
func (_c *TokenWalletLedgerCreate) Save(ctx context.Context) (*TokenWalletLedger, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TokenWalletLedgerCreate) SaveX(ctx context.Context) *TokenWalletLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TokenWalletLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TokenWalletLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TokenWalletLedgerCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if tokenwalletledger.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized tokenwalletledger.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := tokenwalletledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if tokenwalletledger.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized tokenwalletledger.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := tokenwalletledger.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ChannelNameSnapshot(); !ok {
		v := tokenwalletledger.DefaultChannelNameSnapshot
		_c.mutation.SetChannelNameSnapshot(v)
	}
	if _, ok := _c.mutation.EffectiveTokensSnapshot(); !ok {
		v := tokenwalletledger.DefaultEffectiveTokensSnapshot
		_c.mutation.SetEffectiveTokensSnapshot(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TokenWalletLedgerCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TokenWalletLedger.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := tokenwalletledger.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "TokenWalletLedger.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "TokenWalletLedger.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := tokenwalletledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "TokenWalletLedger.request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UsageLogID(); ok {
		if err := tokenwalletledger.UsageLogIDValidator(v); err != nil {
			return &ValidationError{Name: "usage_log_id", err: fmt.Errorf(`ent: validator failed for field "TokenWalletLedger.usage_log_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ChannelID(); ok {
		if err := tokenwalletledger.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "TokenWalletLedger.channel_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChannelNameSnapshot(); !ok {
		return &ValidationError{Name: "channel_name_snapshot", err: errors.New(`ent: missing required field "TokenWalletLedger.channel_name_snapshot"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "TokenWalletLedger.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := tokenwalletledger.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "TokenWalletLedger.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountTokens(); !ok {
		return &ValidationError{Name: "amount_tokens", err: errors.New(`ent: missing required field "TokenWalletLedger.amount_tokens"`)}
	}
	if v, ok := _c.mutation.AmountTokens(); ok {
		if err := tokenwalletledger.AmountTokensValidator(v); err != nil {
			return &ValidationError{Name: "amount_tokens", err: fmt.Errorf(`ent: validator failed for field "TokenWalletLedger.amount_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EffectiveTokensSnapshot(); !ok {
		return &ValidationError{Name: "effective_tokens_snapshot", err: errors.New(`ent: missing required field "TokenWalletLedger.effective_tokens_snapshot"`)}
	}
	if v, ok := _c.mutation.EffectiveTokensSnapshot(); ok {
		if err := tokenwalletledger.EffectiveTokensSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "effective_tokens_snapshot", err: fmt.Errorf(`ent: validator failed for field "TokenWalletLedger.effective_tokens_snapshot": %w`, err)}
		}
	}
	return nil
}

func (_c *TokenWalletLedgerCreate) sqlSave(ctx context.Context) (*TokenWalletLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TokenWalletLedgerCreate) createSpec() (*TokenWalletLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &TokenWalletLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tokenwalletledger.Table, sqlgraph.NewFieldSpec(tokenwalletledger.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tokenwalletledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenwalletledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(tokenwalletledger.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(tokenwalletledger.FieldRequestID, field.TypeInt, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(tokenwalletledger.FieldUsageLogID, field.TypeInt, value)
		_node.UsageLogID = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(tokenwalletledger.FieldChannelID, field.TypeInt, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.ChannelNameSnapshot(); ok {
		_spec.SetField(tokenwalletledger.FieldChannelNameSnapshot, field.TypeString, value)
		_node.ChannelNameSnapshot = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(tokenwalletledger.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.AmountTokens(); ok {
		_spec.SetField(tokenwalletledger.FieldAmountTokens, field.TypeInt64, value)
		_node.AmountTokens = value
	}
	if value, ok := _c.mutation.EffectiveTokensSnapshot(); ok {
		_spec.SetField(tokenwalletledger.FieldEffectiveTokensSnapshot, field.TypeInt64, value)
		_node.EffectiveTokensSnapshot = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TokenWalletLedger.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TokenWalletLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TokenWalletLedgerCreate) OnConflict(opts ...sql.ConflictOption) *TokenWalletLedgerUpsertOne {
	_c.conflict = opts
	return &TokenWalletLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TokenWalletLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TokenWalletLedgerCreate) OnConflictColumns(columns ...string) *TokenWalletLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TokenWalletLedgerUpsertOne{
		create: _c,
	}
}

type (
	// TokenWalletLedgerUpsertOne is the builder for "upsert"-ing
	//  one TokenWalletLedger node.
	TokenWalletLedgerUpsertOne struct {
		create *TokenWalletLedgerCreate
	}

	// TokenWalletLedgerUpsert is the "OnConflict" setter.
	TokenWalletLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TokenWalletLedgerUpsert) SetUpdatedAt(v time.Time) *TokenWalletLedgerUpsert {
	u.Set(tokenwalletledger.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TokenWalletLedgerUpsert) UpdateUpdatedAt() *TokenWalletLedgerUpsert {
	u.SetExcluded(tokenwalletledger.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TokenWalletLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TokenWalletLedgerUpsertOne) UpdateNewValues() *TokenWalletLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tokenwalletledger.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(tokenwalletledger.FieldUserID)
		}
		if _, exists := u.create.mutation.RequestID(); exists {
			s.SetIgnore(tokenwalletledger.FieldRequestID)
		}
		if _, exists := u.create.mutation.UsageLogID(); exists {
			s.SetIgnore(tokenwalletledger.FieldUsageLogID)
		}
		if _, exists := u.create.mutation.ChannelID(); exists {
			s.SetIgnore(tokenwalletledger.FieldChannelID)
		}
		if _, exists := u.create.mutation.ChannelNameSnapshot(); exists {
			s.SetIgnore(tokenwalletledger.FieldChannelNameSnapshot)
		}
		if _, exists := u.create.mutation.Kind(); exists {
			s.SetIgnore(tokenwalletledger.FieldKind)
		}
		if _, exists := u.create.mutation.AmountTokens(); exists {
			s.SetIgnore(tokenwalletledger.FieldAmountTokens)
		}
		if _, exists := u.create.mutation.EffectiveTokensSnapshot(); exists {
			s.SetIgnore(tokenwalletledger.FieldEffectiveTokensSnapshot)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TokenWalletLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TokenWalletLedgerUpsertOne) Ignore() *TokenWalletLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TokenWalletLedgerUpsertOne) DoNothing() *TokenWalletLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TokenWalletLedgerCreate.OnConflict
// documentation for more info.
func (u *TokenWalletLedgerUpsertOne) Update(set func(*TokenWalletLedgerUpsert)) *TokenWalletLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TokenWalletLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TokenWalletLedgerUpsertOne) SetUpdatedAt(v time.Time) *TokenWalletLedgerUpsertOne {
	return u.Update(func(s *TokenWalletLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TokenWalletLedgerUpsertOne) UpdateUpdatedAt() *TokenWalletLedgerUpsertOne {
	return u.Update(func(s *TokenWalletLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TokenWalletLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TokenWalletLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TokenWalletLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TokenWalletLedgerUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TokenWalletLedgerUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TokenWalletLedgerCreateBulk is the builder for creating many TokenWalletLedger entities in bulk.
type TokenWalletLedgerCreateBulk struct {
	config
	err      error
	builders []*TokenWalletLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the TokenWalletLedger entities in the database.
func (_c *TokenWalletLedgerCreateBulk) Save(ctx context.Context) ([]*TokenWalletLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TokenWalletLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TokenWalletLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TokenWalletLedgerCreateBulk) SaveX(ctx context.Context) []*TokenWalletLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TokenWalletLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TokenWalletLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TokenWalletLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TokenWalletLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TokenWalletLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *TokenWalletLedgerUpsertBulk {
	_c.conflict = opts
	return &TokenWalletLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TokenWalletLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TokenWalletLedgerCreateBulk) OnConflictColumns(columns ...string) *TokenWalletLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TokenWalletLedgerUpsertBulk{
		create: _c,
	}
}

// TokenWalletLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of TokenWalletLedger nodes.
type TokenWalletLedgerUpsertBulk struct {
	create *TokenWalletLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TokenWalletLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TokenWalletLedgerUpsertBulk) UpdateNewValues() *TokenWalletLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tokenwalletledger.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(tokenwalletledger.FieldUserID)
			}
			if _, exists := b.mutation.RequestID(); exists {
				s.SetIgnore(tokenwalletledger.FieldRequestID)
			}
			if _, exists := b.mutation.UsageLogID(); exists {
				s.SetIgnore(tokenwalletledger.FieldUsageLogID)
			}
			if _, exists := b.mutation.ChannelID(); exists {
				s.SetIgnore(tokenwalletledger.FieldChannelID)
			}
			if _, exists := b.mutation.ChannelNameSnapshot(); exists {
				s.SetIgnore(tokenwalletledger.FieldChannelNameSnapshot)
			}
			if _, exists := b.mutation.Kind(); exists {
				s.SetIgnore(tokenwalletledger.FieldKind)
			}
			if _, exists := b.mutation.AmountTokens(); exists {
				s.SetIgnore(tokenwalletledger.FieldAmountTokens)
			}
			if _, exists := b.mutation.EffectiveTokensSnapshot(); exists {
				s.SetIgnore(tokenwalletledger.FieldEffectiveTokensSnapshot)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TokenWalletLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TokenWalletLedgerUpsertBulk) Ignore() *TokenWalletLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TokenWalletLedgerUpsertBulk) DoNothing() *TokenWalletLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TokenWalletLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *TokenWalletLedgerUpsertBulk) Update(set func(*TokenWalletLedgerUpsert)) *TokenWalletLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TokenWalletLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TokenWalletLedgerUpsertBulk) SetUpdatedAt(v time.Time) *TokenWalletLedgerUpsertBulk {
	return u.Update(func(s *TokenWalletLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TokenWalletLedgerUpsertBulk) UpdateUpdatedAt() *TokenWalletLedgerUpsertBulk {
	return u.Update(func(s *TokenWalletLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TokenWalletLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TokenWalletLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TokenWalletLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TokenWalletLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
