// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/tokenwalletledger"
)

// TokenWalletLedger is the model entity for the TokenWalletLedger schema.
type TokenWalletLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID int `json:"request_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int `json:"usage_log_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// ChannelNameSnapshot holds the value of the "channel_name_snapshot" field.
	ChannelNameSnapshot string `json:"channel_name_snapshot,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind tokenwalletledger.Kind `json:"kind,omitempty"`
	// AmountTokens holds the value of the "amount_tokens" field.
	AmountTokens int64 `json:"amount_tokens,omitempty"`
	// EffectiveTokensSnapshot holds the value of the "effective_tokens_snapshot" field.
	EffectiveTokensSnapshot int64 `json:"effective_tokens_snapshot,omitempty"`
	selectValues            sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TokenWalletLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tokenwalletledger.FieldID, tokenwalletledger.FieldUserID, tokenwalletledger.FieldRequestID, tokenwalletledger.FieldUsageLogID, tokenwalletledger.FieldChannelID, tokenwalletledger.FieldAmountTokens, tokenwalletledger.FieldEffectiveTokensSnapshot:
			values[i] = new(sql.NullInt64)
		case tokenwalletledger.FieldChannelNameSnapshot, tokenwalletledger.FieldKind:
			values[i] = new(sql.NullString)
		case tokenwalletledger.FieldCreatedAt, tokenwalletledger.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TokenWalletLedger fields.
func (_m *TokenWalletLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tokenwalletledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tokenwalletledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tokenwalletledger.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tokenwalletledger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case tokenwalletledger.FieldRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = int(value.Int64)
			}
		case tokenwalletledger.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = int(value.Int64)
			}
		case tokenwalletledger.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case tokenwalletledger.FieldChannelNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_name_snapshot", values[i])
			} else if value.Valid {
				_m.ChannelNameSnapshot = value.String
			}
		case tokenwalletledger.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = tokenwalletledger.Kind(value.String)
			}
		case tokenwalletledger.FieldAmountTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_tokens", values[i])
			} else if value.Valid {
				_m.AmountTokens = value.Int64
			}
		case tokenwalletledger.FieldEffectiveTokensSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field effective_tokens_snapshot", values[i])
			} else if value.Valid {
				_m.EffectiveTokensSnapshot = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TokenWalletLedger.
// This includes values selected through modifiers, order, etc.
func (_m *TokenWalletLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TokenWalletLedger.
// Note that you need to call TokenWalletLedger.Unwrap() before calling this method if this TokenWalletLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TokenWalletLedger) Update() *TokenWalletLedgerUpdateOne {
	return NewTokenWalletLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TokenWalletLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TokenWalletLedger) Unwrap() *TokenWalletLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TokenWalletLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TokenWalletLedger) String() string {
	var builder strings.Builder
	builder.WriteString("TokenWalletLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("channel_name_snapshot=")
	builder.WriteString(_m.ChannelNameSnapshot)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("amount_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountTokens))
	builder.WriteString(", ")
	builder.WriteString("effective_tokens_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.EffectiveTokensSnapshot))
	builder.WriteByte(')')
	return builder.String()
}

// TokenWalletLedgers is a parsable slice of TokenWalletLedger.
type TokenWalletLedgers []*TokenWalletLedger
