// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/tokenwalletledger"
)

// TokenWalletLedgerUpdate is the builder for updating TokenWalletLedger entities.
type TokenWalletLedgerUpdate struct {
	config
	hooks     []Hook
	mutation  *TokenWalletLedgerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TokenWalletLedgerUpdate builder.
func (_u *TokenWalletLedgerUpdate) Where(ps ...predicate.TokenWalletLedger) *TokenWalletLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenWalletLedgerUpdate) SetUpdatedAt(v time.Time) *TokenWalletLedgerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TokenWalletLedgerMutation object of the builder.
func (_u *TokenWalletLedgerUpdate) Mutation() *TokenWalletLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TokenWalletLedgerUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenWalletLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TokenWalletLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenWalletLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenWalletLedgerUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if tokenwalletledger.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized tokenwalletledger.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := tokenwalletledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TokenWalletLedgerUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TokenWalletLedgerUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TokenWalletLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tokenwalletledger.Table, tokenwalletledger.Columns, sqlgraph.NewFieldSpec(tokenwalletledger.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenwalletledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(tokenwalletledger.FieldUsageLogID, field.TypeInt)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(tokenwalletledger.FieldChannelID, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokenwalletledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TokenWalletLedgerUpdateOne is the builder for updating a single TokenWalletLedger entity.
type TokenWalletLedgerUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TokenWalletLedgerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenWalletLedgerUpdateOne) SetUpdatedAt(v time.Time) *TokenWalletLedgerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TokenWalletLedgerMutation object of the builder.
func (_u *TokenWalletLedgerUpdateOne) Mutation() *TokenWalletLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the TokenWalletLedgerUpdate builder.
func (_u *TokenWalletLedgerUpdateOne) Where(ps ...predicate.TokenWalletLedger) *TokenWalletLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TokenWalletLedgerUpdateOne) Select(field string, fields ...string) *TokenWalletLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TokenWalletLedger entity.
func (_u *TokenWalletLedgerUpdateOne) Save(ctx context.Context) (*TokenWalletLedger, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenWalletLedgerUpdateOne) SaveX(ctx context.Context) *TokenWalletLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TokenWalletLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenWalletLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenWalletLedgerUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if tokenwalletledger.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized tokenwalletledger.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := tokenwalletledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TokenWalletLedgerUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TokenWalletLedgerUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TokenWalletLedgerUpdateOne) sqlSave(ctx context.Context) (_node *TokenWalletLedger, err error) {
	_spec := sqlgraph.NewUpdateSpec(tokenwalletledger.Table, tokenwalletledger.Columns, sqlgraph.NewFieldSpec(tokenwalletledger.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TokenWalletLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenwalletledger.FieldID)
		for _, f := range fields {
			if !tokenwalletledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tokenwalletledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenwalletledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(tokenwalletledger.FieldUsageLogID, field.TypeInt)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(tokenwalletledger.FieldChannelID, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TokenWalletLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokenwalletledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
