// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/usertokenwallet"
)

// UserTokenWalletUpdate is the builder for updating UserTokenWallet entities.
type UserTokenWalletUpdate struct {
	config
	hooks     []Hook
	mutation  *UserTokenWalletMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserTokenWalletUpdate builder.
func (_u *UserTokenWalletUpdate) Where(ps ...predicate.UserTokenWallet) *UserTokenWalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserTokenWalletUpdate) SetUpdatedAt(v time.Time) *UserTokenWalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBalanceTokens sets the "balance_tokens" field.
func (_u *UserTokenWalletUpdate) SetBalanceTokens(v int64) *UserTokenWalletUpdate {
	_u.mutation.ResetBalanceTokens()
	_u.mutation.SetBalanceTokens(v)
	return _u
}

// SetNillableBalanceTokens sets the "balance_tokens" field if the given value is not nil.
func (_u *UserTokenWalletUpdate) SetNillableBalanceTokens(v *int64) *UserTokenWalletUpdate {
	if v != nil {
		_u.SetBalanceTokens(*v)
	}
	return _u
}

// AddBalanceTokens adds value to the "balance_tokens" field.
func (_u *UserTokenWalletUpdate) AddBalanceTokens(v int64) *UserTokenWalletUpdate {
	_u.mutation.AddBalanceTokens(v)
	return _u
}

// SetLifetimeCreditedTokens sets the "lifetime_credited_tokens" field.
func (_u *UserTokenWalletUpdate) SetLifetimeCreditedTokens(v int64) *UserTokenWalletUpdate {
	_u.mutation.ResetLifetimeCreditedTokens()
	_u.mutation.SetLifetimeCreditedTokens(v)
	return _u
}

// SetNillableLifetimeCreditedTokens sets the "lifetime_credited_tokens" field if the given value is not nil.
func (_u *UserTokenWalletUpdate) SetNillableLifetimeCreditedTokens(v *int64) *UserTokenWalletUpdate {
	if v != nil {
		_u.SetLifetimeCreditedTokens(*v)
	}
	return _u
}

// AddLifetimeCreditedTokens adds value to the "lifetime_credited_tokens" field.
func (_u *UserTokenWalletUpdate) AddLifetimeCreditedTokens(v int64) *UserTokenWalletUpdate {
	_u.mutation.AddLifetimeCreditedTokens(v)
	return _u
}

// SetLifetimeDebitedTokens sets the "lifetime_debited_tokens" field.
func (_u *UserTokenWalletUpdate) SetLifetimeDebitedTokens(v int64) *UserTokenWalletUpdate {
	_u.mutation.ResetLifetimeDebitedTokens()
	_u.mutation.SetLifetimeDebitedTokens(v)
	return _u
}

// SetNillableLifetimeDebitedTokens sets the "lifetime_debited_tokens" field if the given value is not nil.
func (_u *UserTokenWalletUpdate) SetNillableLifetimeDebitedTokens(v *int64) *UserTokenWalletUpdate {
	if v != nil {
		_u.SetLifetimeDebitedTokens(*v)
	}
	return _u
}

// AddLifetimeDebitedTokens adds value to the "lifetime_debited_tokens" field.
func (_u *UserTokenWalletUpdate) AddLifetimeDebitedTokens(v int64) *UserTokenWalletUpdate {
	_u.mutation.AddLifetimeDebitedTokens(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserTokenWalletUpdate) SetVersion(v int64) *UserTokenWalletUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserTokenWalletUpdate) SetNillableVersion(v *int64) *UserTokenWalletUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserTokenWalletUpdate) AddVersion(v int64) *UserTokenWalletUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the UserTokenWalletMutation object of the builder.
func (_u *UserTokenWalletUpdate) Mutation() *UserTokenWalletMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserTokenWalletUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTokenWalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserTokenWalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTokenWalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTokenWalletUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usertokenwallet.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usertokenwallet.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usertokenwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTokenWalletUpdate) check() error {
	if v, ok := _u.mutation.BalanceTokens(); ok {
		if err := usertokenwallet.BalanceTokensValidator(v); err != nil {
			return &ValidationError{Name: "balance_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.balance_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeCreditedTokens(); ok {
		if err := usertokenwallet.LifetimeCreditedTokensValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_credited_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.lifetime_credited_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeDebitedTokens(); ok {
		if err := usertokenwallet.LifetimeDebitedTokensValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_debited_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.lifetime_debited_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := usertokenwallet.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.version": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserTokenWalletUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserTokenWalletUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserTokenWalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertokenwallet.Table, usertokenwallet.Columns, sqlgraph.NewFieldSpec(usertokenwallet.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usertokenwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BalanceTokens(); ok {
		_spec.SetField(usertokenwallet.FieldBalanceTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceTokens(); ok {
		_spec.AddField(usertokenwallet.FieldBalanceTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LifetimeCreditedTokens(); ok {
		_spec.SetField(usertokenwallet.FieldLifetimeCreditedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeCreditedTokens(); ok {
		_spec.AddField(usertokenwallet.FieldLifetimeCreditedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LifetimeDebitedTokens(); ok {
		_spec.SetField(usertokenwallet.FieldLifetimeDebitedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeDebitedTokens(); ok {
		_spec.AddField(usertokenwallet.FieldLifetimeDebitedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(usertokenwallet.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(usertokenwallet.FieldVersion, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertokenwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserTokenWalletUpdateOne is the builder for updating a single UserTokenWallet entity.
type UserTokenWalletUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserTokenWalletMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserTokenWalletUpdateOne) SetUpdatedAt(v time.Time) *UserTokenWalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBalanceTokens sets the "balance_tokens" field.
func (_u *UserTokenWalletUpdateOne) SetBalanceTokens(v int64) *UserTokenWalletUpdateOne {
	_u.mutation.ResetBalanceTokens()
	_u.mutation.SetBalanceTokens(v)
	return _u
}

// SetNillableBalanceTokens sets the "balance_tokens" field if the given value is not nil.
func (_u *UserTokenWalletUpdateOne) SetNillableBalanceTokens(v *int64) *UserTokenWalletUpdateOne {
	if v != nil {
		_u.SetBalanceTokens(*v)
	}
	return _u
}

// AddBalanceTokens adds value to the "balance_tokens" field.
func (_u *UserTokenWalletUpdateOne) AddBalanceTokens(v int64) *UserTokenWalletUpdateOne {
	_u.mutation.AddBalanceTokens(v)
	return _u
}

// SetLifetimeCreditedTokens sets the "lifetime_credited_tokens" field.
func (_u *UserTokenWalletUpdateOne) SetLifetimeCreditedTokens(v int64) *UserTokenWalletUpdateOne {
	_u.mutation.ResetLifetimeCreditedTokens()
	_u.mutation.SetLifetimeCreditedTokens(v)
	return _u
}

// SetNillableLifetimeCreditedTokens sets the "lifetime_credited_tokens" field if the given value is not nil.
func (_u *UserTokenWalletUpdateOne) SetNillableLifetimeCreditedTokens(v *int64) *UserTokenWalletUpdateOne {
	if v != nil {
		_u.SetLifetimeCreditedTokens(*v)
	}
	return _u
}

// AddLifetimeCreditedTokens adds value to the "lifetime_credited_tokens" field.
func (_u *UserTokenWalletUpdateOne) AddLifetimeCreditedTokens(v int64) *UserTokenWalletUpdateOne {
	_u.mutation.AddLifetimeCreditedTokens(v)
	return _u
}

// SetLifetimeDebitedTokens sets the "lifetime_debited_tokens" field.
func (_u *UserTokenWalletUpdateOne) SetLifetimeDebitedTokens(v int64) *UserTokenWalletUpdateOne {
	_u.mutation.ResetLifetimeDebitedTokens()
	_u.mutation.SetLifetimeDebitedTokens(v)
	return _u
}

// SetNillableLifetimeDebitedTokens sets the "lifetime_debited_tokens" field if the given value is not nil.
func (_u *UserTokenWalletUpdateOne) SetNillableLifetimeDebitedTokens(v *int64) *UserTokenWalletUpdateOne {
	if v != nil {
		_u.SetLifetimeDebitedTokens(*v)
	}
	return _u
}

// AddLifetimeDebitedTokens adds value to the "lifetime_debited_tokens" field.
func (_u *UserTokenWalletUpdateOne) AddLifetimeDebitedTokens(v int64) *UserTokenWalletUpdateOne {
	_u.mutation.AddLifetimeDebitedTokens(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserTokenWalletUpdateOne) SetVersion(v int64) *UserTokenWalletUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserTokenWalletUpdateOne) SetNillableVersion(v *int64) *UserTokenWalletUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserTokenWalletUpdateOne) AddVersion(v int64) *UserTokenWalletUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the UserTokenWalletMutation object of the builder.
func (_u *UserTokenWalletUpdateOne) Mutation() *UserTokenWalletMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserTokenWalletUpdate builder.
func (_u *UserTokenWalletUpdateOne) Where(ps ...predicate.UserTokenWallet) *UserTokenWalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserTokenWalletUpdateOne) Select(field string, fields ...string) *UserTokenWalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserTokenWallet entity.
func (_u *UserTokenWalletUpdateOne) Save(ctx context.Context) (*UserTokenWallet, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTokenWalletUpdateOne) SaveX(ctx context.Context) *UserTokenWallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserTokenWalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTokenWalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTokenWalletUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usertokenwallet.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usertokenwallet.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usertokenwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTokenWalletUpdateOne) check() error {
	if v, ok := _u.mutation.BalanceTokens(); ok {
		if err := usertokenwallet.BalanceTokensValidator(v); err != nil {
			return &ValidationError{Name: "balance_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.balance_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeCreditedTokens(); ok {
		if err := usertokenwallet.LifetimeCreditedTokensValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_credited_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.lifetime_credited_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LifetimeDebitedTokens(); ok {
		if err := usertokenwallet.LifetimeDebitedTokensValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_debited_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.lifetime_debited_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := usertokenwallet.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.version": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserTokenWalletUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserTokenWalletUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserTokenWalletUpdateOne) sqlSave(ctx context.Context) (_node *UserTokenWallet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertokenwallet.Table, usertokenwallet.Columns, sqlgraph.NewFieldSpec(usertokenwallet.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserTokenWallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertokenwallet.FieldID)
		for _, f := range fields {
			if !usertokenwallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertokenwallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usertokenwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BalanceTokens(); ok {
		_spec.SetField(usertokenwallet.FieldBalanceTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceTokens(); ok {
		_spec.AddField(usertokenwallet.FieldBalanceTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LifetimeCreditedTokens(); ok {
		_spec.SetField(usertokenwallet.FieldLifetimeCreditedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeCreditedTokens(); ok {
		_spec.AddField(usertokenwallet.FieldLifetimeCreditedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LifetimeDebitedTokens(); ok {
		_spec.SetField(usertokenwallet.FieldLifetimeDebitedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeDebitedTokens(); ok {
		_spec.AddField(usertokenwallet.FieldLifetimeDebitedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(usertokenwallet.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(usertokenwallet.FieldVersion, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserTokenWallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertokenwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
