// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/usertokenwallet"
)

// UserTokenWallet is the model entity for the UserTokenWallet schema.
type UserTokenWallet struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// BalanceTokens holds the value of the "balance_tokens" field.
	BalanceTokens int64 `json:"balance_tokens,omitempty"`
	// LifetimeCreditedTokens holds the value of the "lifetime_credited_tokens" field.
	LifetimeCreditedTokens int64 `json:"lifetime_credited_tokens,omitempty"`
	// LifetimeDebitedTokens holds the value of the "lifetime_debited_tokens" field.
	LifetimeDebitedTokens int64 `json:"lifetime_debited_tokens,omitempty"`
	// Version holds the value of the "version" field.
	Version      int64 `json:"version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserTokenWallet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usertokenwallet.FieldID, usertokenwallet.FieldUserID, usertokenwallet.FieldBalanceTokens, usertokenwallet.FieldLifetimeCreditedTokens, usertokenwallet.FieldLifetimeDebitedTokens, usertokenwallet.FieldVersion:
			values[i] = new(sql.NullInt64)
		case usertokenwallet.FieldCreatedAt, usertokenwallet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserTokenWallet fields.
func (_m *UserTokenWallet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usertokenwallet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usertokenwallet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usertokenwallet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usertokenwallet.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case usertokenwallet.FieldBalanceTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_tokens", values[i])
			} else if value.Valid {
				_m.BalanceTokens = value.Int64
			}
		case usertokenwallet.FieldLifetimeCreditedTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_credited_tokens", values[i])
			} else if value.Valid {
				_m.LifetimeCreditedTokens = value.Int64
			}
		case usertokenwallet.FieldLifetimeDebitedTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_debited_tokens", values[i])
			} else if value.Valid {
				_m.LifetimeDebitedTokens = value.Int64
			}
		case usertokenwallet.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserTokenWallet.
// This includes values selected through modifiers, order, etc.
func (_m *UserTokenWallet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserTokenWallet.
// Note that you need to call UserTokenWallet.Unwrap() before calling this method if this UserTokenWallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserTokenWallet) Update() *UserTokenWalletUpdateOne {
	return NewUserTokenWalletClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserTokenWallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserTokenWallet) Unwrap() *UserTokenWallet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserTokenWallet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserTokenWallet) String() string {
	var builder strings.Builder
	builder.WriteString("UserTokenWallet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("balance_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceTokens))
	builder.WriteString(", ")
	builder.WriteString("lifetime_credited_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.LifetimeCreditedTokens))
	builder.WriteString(", ")
	builder.WriteString("lifetime_debited_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.LifetimeDebitedTokens))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// UserTokenWallets is a parsable slice of UserTokenWallet.
type UserTokenWallets []*UserTokenWallet
