// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/usertokenwallet"
)

// UserTokenWalletDelete is the builder for deleting a UserTokenWallet entity.
type UserTokenWalletDelete struct {
	config
	hooks    []Hook
	mutation *UserTokenWalletMutation
}

// Where appends a list predicates to the UserTokenWalletDelete builder.
func (_d *UserTokenWalletDelete) Where(ps ...predicate.UserTokenWallet) *UserTokenWalletDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserTokenWalletDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserTokenWalletDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserTokenWalletDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usertokenwallet.Table, sqlgraph.NewFieldSpec(usertokenwallet.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserTokenWalletDeleteOne is the builder for deleting a single UserTokenWallet entity.
type UserTokenWalletDeleteOne struct {
	_d *UserTokenWalletDelete
}

// Where appends a list predicates to the UserTokenWalletDelete builder.
func (_d *UserTokenWalletDeleteOne) Where(ps ...predicate.UserTokenWallet) *UserTokenWalletDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserTokenWalletDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usertokenwallet.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserTokenWalletDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
