// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/usertokenwallet"
)

// UserTokenWalletCreate is the builder for creating a UserTokenWallet entity.
type UserTokenWalletCreate struct {
	config
	mutation *UserTokenWalletMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserTokenWalletCreate) SetCreatedAt(v time.Time) *UserTokenWalletCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserTokenWalletCreate) SetNillableCreatedAt(v *time.Time) *UserTokenWalletCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserTokenWalletCreate) SetUpdatedAt(v time.Time) *UserTokenWalletCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserTokenWalletCreate) SetNillableUpdatedAt(v *time.Time) *UserTokenWalletCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserTokenWalletCreate) SetUserID(v int) *UserTokenWalletCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBalanceTokens sets the "balance_tokens" field.
func (_c *UserTokenWalletCreate) SetBalanceTokens(v int64) *UserTokenWalletCreate {
	_c.mutation.SetBalanceTokens(v)
	return _c
}

// SetNillableBalanceTokens sets the "balance_tokens" field if the given value is not nil.
func (_c *UserTokenWalletCreate) SetNillableBalanceTokens(v *int64) *UserTokenWalletCreate {
	if v != nil {
		_c.SetBalanceTokens(*v)
	}
	return _c
}

// SetLifetimeCreditedTokens sets the "lifetime_credited_tokens" field.
func (_c *UserTokenWalletCreate) SetLifetimeCreditedTokens(v int64) *UserTokenWalletCreate {
	_c.mutation.SetLifetimeCreditedTokens(v)
	return _c
}

// SetNillableLifetimeCreditedTokens sets the "lifetime_credited_tokens" field if the given value is not nil.
func (_c *UserTokenWalletCreate) SetNillableLifetimeCreditedTokens(v *int64) *UserTokenWalletCreate {
	if v != nil {
		_c.SetLifetimeCreditedTokens(*v)
	}
	return _c
}

// SetLifetimeDebitedTokens sets the "lifetime_debited_tokens" field.
func (_c *UserTokenWalletCreate) SetLifetimeDebitedTokens(v int64) *UserTokenWalletCreate {
	_c.mutation.SetLifetimeDebitedTokens(v)
	return _c
}

// SetNillableLifetimeDebitedTokens sets the "lifetime_debited_tokens" field if the given value is not nil.
func (_c *UserTokenWalletCreate) SetNillableLifetimeDebitedTokens(v *int64) *UserTokenWalletCreate {
	if v != nil {
		_c.SetLifetimeDebitedTokens(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *UserTokenWalletCreate) SetVersion(v int64) *UserTokenWalletCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *UserTokenWalletCreate) SetNillableVersion(v *int64) *UserTokenWalletCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// Mutation returns the UserTokenWalletMutation object of the builder.
func (_c *UserTokenWalletCreate) Mutation() *UserTokenWalletMutation {
	return _c.mutation
}

// Save creates the UserTokenWallet in the database.
func (_c *UserTokenWalletCreate) Save(ctx context.Context) (*UserTokenWallet, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserTokenWalletCreate) SaveX(ctx context.Context) *UserTokenWallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTokenWalletCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTokenWalletCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserTokenWalletCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if usertokenwallet.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized usertokenwallet.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := usertokenwallet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if usertokenwallet.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usertokenwallet.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usertokenwallet.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.BalanceTokens(); !ok {
		v := usertokenwallet.DefaultBalanceTokens
		_c.mutation.SetBalanceTokens(v)
	}
	if _, ok := _c.mutation.LifetimeCreditedTokens(); !ok {
		v := usertokenwallet.DefaultLifetimeCreditedTokens
		_c.mutation.SetLifetimeCreditedTokens(v)
	}
	if _, ok := _c.mutation.LifetimeDebitedTokens(); !ok {
		v := usertokenwallet.DefaultLifetimeDebitedTokens
		_c.mutation.SetLifetimeDebitedTokens(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := usertokenwallet.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserTokenWalletCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserTokenWallet.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := usertokenwallet.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceTokens(); !ok {
		return &ValidationError{Name: "balance_tokens", err: errors.New(`ent: missing required field "UserTokenWallet.balance_tokens"`)}
	}
	if v, ok := _c.mutation.BalanceTokens(); ok {
		if err := usertokenwallet.BalanceTokensValidator(v); err != nil {
			return &ValidationError{Name: "balance_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.balance_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LifetimeCreditedTokens(); !ok {
		return &ValidationError{Name: "lifetime_credited_tokens", err: errors.New(`ent: missing required field "UserTokenWallet.lifetime_credited_tokens"`)}
	}
	if v, ok := _c.mutation.LifetimeCreditedTokens(); ok {
		if err := usertokenwallet.LifetimeCreditedTokensValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_credited_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.lifetime_credited_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LifetimeDebitedTokens(); !ok {
		return &ValidationError{Name: "lifetime_debited_tokens", err: errors.New(`ent: missing required field "UserTokenWallet.lifetime_debited_tokens"`)}
	}
	if v, ok := _c.mutation.LifetimeDebitedTokens(); ok {
		if err := usertokenwallet.LifetimeDebitedTokensValidator(v); err != nil {
			return &ValidationError{Name: "lifetime_debited_tokens", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.lifetime_debited_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "UserTokenWallet.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := usertokenwallet.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "UserTokenWallet.version": %w`, err)}
		}
	}
	return nil
}

func (_c *UserTokenWalletCreate) sqlSave(ctx context.Context) (*UserTokenWallet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserTokenWalletCreate) createSpec() (*UserTokenWallet, *sqlgraph.CreateSpec) {
	var (
		_node = &UserTokenWallet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usertokenwallet.Table, sqlgraph.NewFieldSpec(usertokenwallet.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usertokenwallet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usertokenwallet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usertokenwallet.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.BalanceTokens(); ok {
		_spec.SetField(usertokenwallet.FieldBalanceTokens, field.TypeInt64, value)
		_node.BalanceTokens = value
	}
	if value, ok := _c.mutation.LifetimeCreditedTokens(); ok {
		_spec.SetField(usertokenwallet.FieldLifetimeCreditedTokens, field.TypeInt64, value)
		_node.LifetimeCreditedTokens = value
	}
	if value, ok := _c.mutation.LifetimeDebitedTokens(); ok {
		_spec.SetField(usertokenwallet.FieldLifetimeDebitedTokens, field.TypeInt64, value)
		_node.LifetimeDebitedTokens = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(usertokenwallet.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserTokenWallet.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserTokenWalletUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserTokenWalletCreate) OnConflict(opts ...sql.ConflictOption) *UserTokenWalletUpsertOne {
	_c.conflict = opts
	return &UserTokenWalletUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserTokenWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserTokenWalletCreate) OnConflictColumns(columns ...string) *UserTokenWalletUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserTokenWalletUpsertOne{
		create: _c,
	}
}

type (
	// UserTokenWalletUpsertOne is the builder for "upsert"-ing
	//  one UserTokenWallet node.
	UserTokenWalletUpsertOne struct {
		create *UserTokenWalletCreate
	}

	// UserTokenWalletUpsert is the "OnConflict" setter.
	UserTokenWalletUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserTokenWalletUpsert) SetUpdatedAt(v time.Time) *UserTokenWalletUpsert {
	u.Set(usertokenwallet.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserTokenWalletUpsert) UpdateUpdatedAt() *UserTokenWalletUpsert {
	u.SetExcluded(usertokenwallet.FieldUpdatedAt)
	return u
}

// SetBalanceTokens sets the "balance_tokens" field.
func (u *UserTokenWalletUpsert) SetBalanceTokens(v int64) *UserTokenWalletUpsert {
	u.Set(usertokenwallet.FieldBalanceTokens, v)
	return u
}

// UpdateBalanceTokens sets the "balance_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsert) UpdateBalanceTokens() *UserTokenWalletUpsert {
	u.SetExcluded(usertokenwallet.FieldBalanceTokens)
	return u
}

// AddBalanceTokens adds v to the "balance_tokens" field.
func (u *UserTokenWalletUpsert) AddBalanceTokens(v int64) *UserTokenWalletUpsert {
	u.Add(usertokenwallet.FieldBalanceTokens, v)
	return u
}

// SetLifetimeCreditedTokens sets the "lifetime_credited_tokens" field.
func (u *UserTokenWalletUpsert) SetLifetimeCreditedTokens(v int64) *UserTokenWalletUpsert {
	u.Set(usertokenwallet.FieldLifetimeCreditedTokens, v)
	return u
}

// UpdateLifetimeCreditedTokens sets the "lifetime_credited_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsert) UpdateLifetimeCreditedTokens() *UserTokenWalletUpsert {
	u.SetExcluded(usertokenwallet.FieldLifetimeCreditedTokens)
	return u
}

// AddLifetimeCreditedTokens adds v to the "lifetime_credited_tokens" field.
func (u *UserTokenWalletUpsert) AddLifetimeCreditedTokens(v int64) *UserTokenWalletUpsert {
	u.Add(usertokenwallet.FieldLifetimeCreditedTokens, v)
	return u
}

// SetLifetimeDebitedTokens sets the "lifetime_debited_tokens" field.
func (u *UserTokenWalletUpsert) SetLifetimeDebitedTokens(v int64) *UserTokenWalletUpsert {
	u.Set(usertokenwallet.FieldLifetimeDebitedTokens, v)
	return u
}

// UpdateLifetimeDebitedTokens sets the "lifetime_debited_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsert) UpdateLifetimeDebitedTokens() *UserTokenWalletUpsert {
	u.SetExcluded(usertokenwallet.FieldLifetimeDebitedTokens)
	return u
}

// AddLifetimeDebitedTokens adds v to the "lifetime_debited_tokens" field.
func (u *UserTokenWalletUpsert) AddLifetimeDebitedTokens(v int64) *UserTokenWalletUpsert {
	u.Add(usertokenwallet.FieldLifetimeDebitedTokens, v)
	return u
}

// SetVersion sets the "version" field.
func (u *UserTokenWalletUpsert) SetVersion(v int64) *UserTokenWalletUpsert {
	u.Set(usertokenwallet.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserTokenWalletUpsert) UpdateVersion() *UserTokenWalletUpsert {
	u.SetExcluded(usertokenwallet.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *UserTokenWalletUpsert) AddVersion(v int64) *UserTokenWalletUpsert {
	u.Add(usertokenwallet.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserTokenWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserTokenWalletUpsertOne) UpdateNewValues() *UserTokenWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usertokenwallet.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(usertokenwallet.FieldUserID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserTokenWallet.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserTokenWalletUpsertOne) Ignore() *UserTokenWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserTokenWalletUpsertOne) DoNothing() *UserTokenWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserTokenWalletCreate.OnConflict
// documentation for more info.
func (u *UserTokenWalletUpsertOne) Update(set func(*UserTokenWalletUpsert)) *UserTokenWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserTokenWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserTokenWalletUpsertOne) SetUpdatedAt(v time.Time) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserTokenWalletUpsertOne) UpdateUpdatedAt() *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBalanceTokens sets the "balance_tokens" field.
func (u *UserTokenWalletUpsertOne) SetBalanceTokens(v int64) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetBalanceTokens(v)
	})
}

// AddBalanceTokens adds v to the "balance_tokens" field.
func (u *UserTokenWalletUpsertOne) AddBalanceTokens(v int64) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.AddBalanceTokens(v)
	})
}

// UpdateBalanceTokens sets the "balance_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsertOne) UpdateBalanceTokens() *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateBalanceTokens()
	})
}

// SetLifetimeCreditedTokens sets the "lifetime_credited_tokens" field.
func (u *UserTokenWalletUpsertOne) SetLifetimeCreditedTokens(v int64) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetLifetimeCreditedTokens(v)
	})
}

// AddLifetimeCreditedTokens adds v to the "lifetime_credited_tokens" field.
func (u *UserTokenWalletUpsertOne) AddLifetimeCreditedTokens(v int64) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.AddLifetimeCreditedTokens(v)
	})
}

// UpdateLifetimeCreditedTokens sets the "lifetime_credited_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsertOne) UpdateLifetimeCreditedTokens() *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateLifetimeCreditedTokens()
	})
}

// SetLifetimeDebitedTokens sets the "lifetime_debited_tokens" field.
func (u *UserTokenWalletUpsertOne) SetLifetimeDebitedTokens(v int64) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetLifetimeDebitedTokens(v)
	})
}

// AddLifetimeDebitedTokens adds v to the "lifetime_debited_tokens" field.
func (u *UserTokenWalletUpsertOne) AddLifetimeDebitedTokens(v int64) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.AddLifetimeDebitedTokens(v)
	})
}

// UpdateLifetimeDebitedTokens sets the "lifetime_debited_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsertOne) UpdateLifetimeDebitedTokens() *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateLifetimeDebitedTokens()
	})
}

// SetVersion sets the "version" field.
func (u *UserTokenWalletUpsertOne) SetVersion(v int64) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *UserTokenWalletUpsertOne) AddVersion(v int64) *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserTokenWalletUpsertOne) UpdateVersion() *UserTokenWalletUpsertOne {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *UserTokenWalletUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserTokenWalletCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserTokenWalletUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserTokenWalletUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserTokenWalletUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserTokenWalletCreateBulk is the builder for creating many UserTokenWallet entities in bulk.
type UserTokenWalletCreateBulk struct {
	config
	err      error
	builders []*UserTokenWalletCreate
	conflict []sql.ConflictOption
}

// Save creates the UserTokenWallet entities in the database.
func (_c *UserTokenWalletCreateBulk) Save(ctx context.Context) ([]*UserTokenWallet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserTokenWallet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserTokenWalletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserTokenWalletCreateBulk) SaveX(ctx context.Context) []*UserTokenWallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTokenWalletCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTokenWalletCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserTokenWallet.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserTokenWalletUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserTokenWalletCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserTokenWalletUpsertBulk {
	_c.conflict = opts
	return &UserTokenWalletUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserTokenWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserTokenWalletCreateBulk) OnConflictColumns(columns ...string) *UserTokenWalletUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserTokenWalletUpsertBulk{
		create: _c,
	}
}

// UserTokenWalletUpsertBulk is the builder for "upsert"-ing
// a bulk of UserTokenWallet nodes.
type UserTokenWalletUpsertBulk struct {
	create *UserTokenWalletCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserTokenWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserTokenWalletUpsertBulk) UpdateNewValues() *UserTokenWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usertokenwallet.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(usertokenwallet.FieldUserID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserTokenWallet.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserTokenWalletUpsertBulk) Ignore() *UserTokenWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserTokenWalletUpsertBulk) DoNothing() *UserTokenWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserTokenWalletCreateBulk.OnConflict
// documentation for more info.
func (u *UserTokenWalletUpsertBulk) Update(set func(*UserTokenWalletUpsert)) *UserTokenWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserTokenWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserTokenWalletUpsertBulk) SetUpdatedAt(v time.Time) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserTokenWalletUpsertBulk) UpdateUpdatedAt() *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBalanceTokens sets the "balance_tokens" field.
func (u *UserTokenWalletUpsertBulk) SetBalanceTokens(v int64) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetBalanceTokens(v)
	})
}

// AddBalanceTokens adds v to the "balance_tokens" field.
func (u *UserTokenWalletUpsertBulk) AddBalanceTokens(v int64) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.AddBalanceTokens(v)
	})
}

// UpdateBalanceTokens sets the "balance_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsertBulk) UpdateBalanceTokens() *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateBalanceTokens()
	})
}

// SetLifetimeCreditedTokens sets the "lifetime_credited_tokens" field.
func (u *UserTokenWalletUpsertBulk) SetLifetimeCreditedTokens(v int64) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetLifetimeCreditedTokens(v)
	})
}

// AddLifetimeCreditedTokens adds v to the "lifetime_credited_tokens" field.
func (u *UserTokenWalletUpsertBulk) AddLifetimeCreditedTokens(v int64) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.AddLifetimeCreditedTokens(v)
	})
}

// UpdateLifetimeCreditedTokens sets the "lifetime_credited_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsertBulk) UpdateLifetimeCreditedTokens() *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateLifetimeCreditedTokens()
	})
}

// SetLifetimeDebitedTokens sets the "lifetime_debited_tokens" field.
func (u *UserTokenWalletUpsertBulk) SetLifetimeDebitedTokens(v int64) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetLifetimeDebitedTokens(v)
	})
}

// AddLifetimeDebitedTokens adds v to the "lifetime_debited_tokens" field.
func (u *UserTokenWalletUpsertBulk) AddLifetimeDebitedTokens(v int64) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.AddLifetimeDebitedTokens(v)
	})
}

// UpdateLifetimeDebitedTokens sets the "lifetime_debited_tokens" field to the value that was provided on create.
func (u *UserTokenWalletUpsertBulk) UpdateLifetimeDebitedTokens() *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateLifetimeDebitedTokens()
	})
}

// SetVersion sets the "version" field.
func (u *UserTokenWalletUpsertBulk) SetVersion(v int64) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *UserTokenWalletUpsertBulk) AddVersion(v int64) *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserTokenWalletUpsertBulk) UpdateVersion() *UserTokenWalletUpsertBulk {
	return u.Update(func(s *UserTokenWalletUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *UserTokenWalletUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserTokenWalletCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserTokenWalletCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserTokenWalletUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
