// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/usertokenwallet"
)

// UserTokenWalletQuery is the builder for querying UserTokenWallet entities.
type UserTokenWalletQuery struct {
	config
	ctx        *QueryContext
	order      []usertokenwallet.OrderOption
	inters     []Interceptor
	predicates []predicate.UserTokenWallet
	loadTotal  []func(context.Context, []*UserTokenWallet) error
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserTokenWalletQuery builder.
func (_q *UserTokenWalletQuery) Where(ps ...predicate.UserTokenWallet) *UserTokenWalletQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UserTokenWalletQuery) Limit(limit int) *UserTokenWalletQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UserTokenWalletQuery) Offset(offset int) *UserTokenWalletQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UserTokenWalletQuery) Unique(unique bool) *UserTokenWalletQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UserTokenWalletQuery) Order(o ...usertokenwallet.OrderOption) *UserTokenWalletQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first UserTokenWallet entity from the query.
// Returns a *NotFoundError when no UserTokenWallet was found.
func (_q *UserTokenWalletQuery) First(ctx context.Context) (*UserTokenWallet, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usertokenwallet.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UserTokenWalletQuery) FirstX(ctx context.Context) *UserTokenWallet {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserTokenWallet ID from the query.
// Returns a *NotFoundError when no UserTokenWallet ID was found.
func (_q *UserTokenWalletQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usertokenwallet.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UserTokenWalletQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserTokenWallet entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserTokenWallet entity is found.
// Returns a *NotFoundError when no UserTokenWallet entities are found.
func (_q *UserTokenWalletQuery) Only(ctx context.Context) (*UserTokenWallet, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usertokenwallet.Label}
	default:
		return nil, &NotSingularError{usertokenwallet.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UserTokenWalletQuery) OnlyX(ctx context.Context) *UserTokenWallet {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserTokenWallet ID in the query.
// Returns a *NotSingularError when more than one UserTokenWallet ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UserTokenWalletQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usertokenwallet.Label}
	default:
		err = &NotSingularError{usertokenwallet.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UserTokenWalletQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserTokenWallets.
func (_q *UserTokenWalletQuery) All(ctx context.Context) ([]*UserTokenWallet, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserTokenWallet, *UserTokenWalletQuery]()
	return withInterceptors[[]*UserTokenWallet](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UserTokenWalletQuery) AllX(ctx context.Context) []*UserTokenWallet {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserTokenWallet IDs.
func (_q *UserTokenWalletQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(usertokenwallet.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UserTokenWalletQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UserTokenWalletQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UserTokenWalletQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UserTokenWalletQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UserTokenWalletQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UserTokenWalletQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserTokenWalletQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UserTokenWalletQuery) Clone() *UserTokenWalletQuery {
	if _q == nil {
		return nil
	}
	return &UserTokenWalletQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]usertokenwallet.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.UserTokenWallet{}, _q.predicates...),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserTokenWallet.Query().
//		GroupBy(usertokenwallet.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UserTokenWalletQuery) GroupBy(field string, fields ...string) *UserTokenWalletGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserTokenWalletGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = usertokenwallet.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UserTokenWallet.Query().
//		Select(usertokenwallet.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *UserTokenWalletQuery) Select(fields ...string) *UserTokenWalletSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UserTokenWalletSelect{UserTokenWalletQuery: _q}
	sbuild.label = usertokenwallet.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserTokenWalletSelect configured with the given aggregations.
func (_q *UserTokenWalletQuery) Aggregate(fns ...AggregateFunc) *UserTokenWalletSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UserTokenWalletQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !usertokenwallet.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if usertokenwallet.Policy == nil {
		return errors.New("ent: uninitialized usertokenwallet.Policy (forgotten import ent/runtime?)")
	}
	if err := usertokenwallet.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *UserTokenWalletQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserTokenWallet, error) {
	var (
		nodes = []*UserTokenWallet{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserTokenWallet).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserTokenWallet{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UserTokenWalletQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UserTokenWalletQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usertokenwallet.Table, usertokenwallet.Columns, sqlgraph.NewFieldSpec(usertokenwallet.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertokenwallet.FieldID)
		for i := range fields {
			if fields[i] != usertokenwallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UserTokenWalletQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(usertokenwallet.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = usertokenwallet.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *UserTokenWalletQuery) Modify(modifiers ...func(s *sql.Selector)) *UserTokenWalletSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// UserTokenWalletGroupBy is the group-by builder for UserTokenWallet entities.
type UserTokenWalletGroupBy struct {
	selector
	build *UserTokenWalletQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UserTokenWalletGroupBy) Aggregate(fns ...AggregateFunc) *UserTokenWalletGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UserTokenWalletGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserTokenWalletQuery, *UserTokenWalletGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UserTokenWalletGroupBy) sqlScan(ctx context.Context, root *UserTokenWalletQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserTokenWalletSelect is the builder for selecting fields of UserTokenWallet entities.
type UserTokenWalletSelect struct {
	*UserTokenWalletQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UserTokenWalletSelect) Aggregate(fns ...AggregateFunc) *UserTokenWalletSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UserTokenWalletSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserTokenWalletQuery, *UserTokenWalletSelect](ctx, _s.UserTokenWalletQuery, _s, _s.inters, v)
}

func (_s *UserTokenWalletSelect) sqlScan(ctx context.Context, root *UserTokenWalletQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *UserTokenWalletSelect) Modify(modifiers ...func(s *sql.Selector)) *UserTokenWalletSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
