// Code generated by ent, DO NOT EDIT.

package emailverificationchallenge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldUpdatedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldEmail, v))
}

// CodeDigest applies equality check predicate on the "code_digest" field. It's identical to CodeDigestEQ.
func CodeDigest(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldCodeDigest, v))
}

// SourceHash applies equality check predicate on the "source_hash" field. It's identical to SourceHashEQ.
func SourceHash(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldSourceHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldExpiresAt, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldAttempts, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldContainsFold(FieldEmail, v))
}

// CodeDigestEQ applies the EQ predicate on the "code_digest" field.
func CodeDigestEQ(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldCodeDigest, v))
}

// CodeDigestNEQ applies the NEQ predicate on the "code_digest" field.
func CodeDigestNEQ(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldCodeDigest, v))
}

// CodeDigestIn applies the In predicate on the "code_digest" field.
func CodeDigestIn(vs ...string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldCodeDigest, vs...))
}

// CodeDigestNotIn applies the NotIn predicate on the "code_digest" field.
func CodeDigestNotIn(vs ...string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldCodeDigest, vs...))
}

// CodeDigestGT applies the GT predicate on the "code_digest" field.
func CodeDigestGT(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldCodeDigest, v))
}

// CodeDigestGTE applies the GTE predicate on the "code_digest" field.
func CodeDigestGTE(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldCodeDigest, v))
}

// CodeDigestLT applies the LT predicate on the "code_digest" field.
func CodeDigestLT(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldCodeDigest, v))
}

// CodeDigestLTE applies the LTE predicate on the "code_digest" field.
func CodeDigestLTE(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldCodeDigest, v))
}

// CodeDigestContains applies the Contains predicate on the "code_digest" field.
func CodeDigestContains(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldContains(FieldCodeDigest, v))
}

// CodeDigestHasPrefix applies the HasPrefix predicate on the "code_digest" field.
func CodeDigestHasPrefix(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldHasPrefix(FieldCodeDigest, v))
}

// CodeDigestHasSuffix applies the HasSuffix predicate on the "code_digest" field.
func CodeDigestHasSuffix(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldHasSuffix(FieldCodeDigest, v))
}

// CodeDigestEqualFold applies the EqualFold predicate on the "code_digest" field.
func CodeDigestEqualFold(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEqualFold(FieldCodeDigest, v))
}

// CodeDigestContainsFold applies the ContainsFold predicate on the "code_digest" field.
func CodeDigestContainsFold(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldContainsFold(FieldCodeDigest, v))
}

// SourceHashEQ applies the EQ predicate on the "source_hash" field.
func SourceHashEQ(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldSourceHash, v))
}

// SourceHashNEQ applies the NEQ predicate on the "source_hash" field.
func SourceHashNEQ(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldSourceHash, v))
}

// SourceHashIn applies the In predicate on the "source_hash" field.
func SourceHashIn(vs ...string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldSourceHash, vs...))
}

// SourceHashNotIn applies the NotIn predicate on the "source_hash" field.
func SourceHashNotIn(vs ...string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldSourceHash, vs...))
}

// SourceHashGT applies the GT predicate on the "source_hash" field.
func SourceHashGT(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldSourceHash, v))
}

// SourceHashGTE applies the GTE predicate on the "source_hash" field.
func SourceHashGTE(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldSourceHash, v))
}

// SourceHashLT applies the LT predicate on the "source_hash" field.
func SourceHashLT(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldSourceHash, v))
}

// SourceHashLTE applies the LTE predicate on the "source_hash" field.
func SourceHashLTE(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldSourceHash, v))
}

// SourceHashContains applies the Contains predicate on the "source_hash" field.
func SourceHashContains(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldContains(FieldSourceHash, v))
}

// SourceHashHasPrefix applies the HasPrefix predicate on the "source_hash" field.
func SourceHashHasPrefix(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldHasPrefix(FieldSourceHash, v))
}

// SourceHashHasSuffix applies the HasSuffix predicate on the "source_hash" field.
func SourceHashHasSuffix(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldHasSuffix(FieldSourceHash, v))
}

// SourceHashEqualFold applies the EqualFold predicate on the "source_hash" field.
func SourceHashEqualFold(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEqualFold(FieldSourceHash, v))
}

// SourceHashContainsFold applies the ContainsFold predicate on the "source_hash" field.
func SourceHashContainsFold(v string) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldContainsFold(FieldSourceHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldExpiresAt, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldAttempts, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.FieldNotNull(FieldConsumedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailVerificationChallenge) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailVerificationChallenge) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailVerificationChallenge) predicate.EmailVerificationChallenge {
	return predicate.EmailVerificationChallenge(sql.NotPredicates(p))
}
