package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/server/biz"
)

// UpdateUserDailyQuotaSettings is the resolver for the updateUserDailyQuotaSettings field.
func (r *mutationResolver) UpdateUserDailyQuotaSettings(ctx context.Context, input UpdateUserDailyQuotaSettingsInput) (bool, error) {
	if err := requireUserDailyQuotaSettingsOwner(ctx); err != nil {
		return false, err
	}

	if err := r.systemService.SetUserDailyQuotaSettings(ctx, biz.UserDailyQuotaSettings{
		DailyTokenLimit: int64(input.DailyTokenLimit),
	}); err != nil {
		return false, fmt.Errorf("failed to update user daily quota settings: %w", err)
	}

	return true, nil
}

// UserDailyQuotaSettings is the resolver for the userDailyQuotaSettings field.
func (r *queryResolver) UserDailyQuotaSettings(ctx context.Context) (*biz.UserDailyQuotaSettings, error) {
	if err := requireUserDailyQuotaSettingsOwner(ctx); err != nil {
		return nil, err
	}

	settings, err := r.systemService.UserDailyQuotaSettings(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user daily quota settings: %w", err)
	}

	return settings, nil
}
