// Code generated by ent, DO NOT EDIT.

package usertokenwallet

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usertokenwallet type in the database.
	Label = "user_token_wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldBalanceTokens holds the string denoting the balance_tokens field in the database.
	FieldBalanceTokens = "balance_tokens"
	// FieldLifetimeCreditedTokens holds the string denoting the lifetime_credited_tokens field in the database.
	FieldLifetimeCreditedTokens = "lifetime_credited_tokens"
	// FieldLifetimeDebitedTokens holds the string denoting the lifetime_debited_tokens field in the database.
	FieldLifetimeDebitedTokens = "lifetime_debited_tokens"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// Table holds the table name of the usertokenwallet in the database.
	Table = "user_token_wallets"
)

// Columns holds all SQL columns for usertokenwallet fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldBalanceTokens,
	FieldLifetimeCreditedTokens,
	FieldLifetimeDebitedTokens,
	FieldVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int) error
	// DefaultBalanceTokens holds the default value on creation for the "balance_tokens" field.
	DefaultBalanceTokens int64
	// BalanceTokensValidator is a validator for the "balance_tokens" field. It is called by the builders before save.
	BalanceTokensValidator func(int64) error
	// DefaultLifetimeCreditedTokens holds the default value on creation for the "lifetime_credited_tokens" field.
	DefaultLifetimeCreditedTokens int64
	// LifetimeCreditedTokensValidator is a validator for the "lifetime_credited_tokens" field. It is called by the builders before save.
	LifetimeCreditedTokensValidator func(int64) error
	// DefaultLifetimeDebitedTokens holds the default value on creation for the "lifetime_debited_tokens" field.
	DefaultLifetimeDebitedTokens int64
	// LifetimeDebitedTokensValidator is a validator for the "lifetime_debited_tokens" field. It is called by the builders before save.
	LifetimeDebitedTokensValidator func(int64) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int64) error
)

// OrderOption defines the ordering options for the UserTokenWallet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByBalanceTokens orders the results by the balance_tokens field.
func ByBalanceTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceTokens, opts...).ToFunc()
}

// ByLifetimeCreditedTokens orders the results by the lifetime_credited_tokens field.
func ByLifetimeCreditedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifetimeCreditedTokens, opts...).ToFunc()
}

// ByLifetimeDebitedTokens orders the results by the lifetime_debited_tokens field.
func ByLifetimeDebitedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifetimeDebitedTokens, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}
