// Code generated by ent, DO NOT EDIT.

package usertokenwallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldUserID, v))
}

// BalanceTokens applies equality check predicate on the "balance_tokens" field. It's identical to BalanceTokensEQ.
func BalanceTokens(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldBalanceTokens, v))
}

// LifetimeCreditedTokens applies equality check predicate on the "lifetime_credited_tokens" field. It's identical to LifetimeCreditedTokensEQ.
func LifetimeCreditedTokens(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldLifetimeCreditedTokens, v))
}

// LifetimeDebitedTokens applies equality check predicate on the "lifetime_debited_tokens" field. It's identical to LifetimeDebitedTokensEQ.
func LifetimeDebitedTokens(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldLifetimeDebitedTokens, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLTE(FieldUserID, v))
}

// BalanceTokensEQ applies the EQ predicate on the "balance_tokens" field.
func BalanceTokensEQ(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldBalanceTokens, v))
}

// BalanceTokensNEQ applies the NEQ predicate on the "balance_tokens" field.
func BalanceTokensNEQ(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNEQ(FieldBalanceTokens, v))
}

// BalanceTokensIn applies the In predicate on the "balance_tokens" field.
func BalanceTokensIn(vs ...int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldIn(FieldBalanceTokens, vs...))
}

// BalanceTokensNotIn applies the NotIn predicate on the "balance_tokens" field.
func BalanceTokensNotIn(vs ...int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNotIn(FieldBalanceTokens, vs...))
}

// BalanceTokensGT applies the GT predicate on the "balance_tokens" field.
func BalanceTokensGT(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGT(FieldBalanceTokens, v))
}

// BalanceTokensGTE applies the GTE predicate on the "balance_tokens" field.
func BalanceTokensGTE(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGTE(FieldBalanceTokens, v))
}

// BalanceTokensLT applies the LT predicate on the "balance_tokens" field.
func BalanceTokensLT(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLT(FieldBalanceTokens, v))
}

// BalanceTokensLTE applies the LTE predicate on the "balance_tokens" field.
func BalanceTokensLTE(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLTE(FieldBalanceTokens, v))
}

// LifetimeCreditedTokensEQ applies the EQ predicate on the "lifetime_credited_tokens" field.
func LifetimeCreditedTokensEQ(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldLifetimeCreditedTokens, v))
}

// LifetimeCreditedTokensNEQ applies the NEQ predicate on the "lifetime_credited_tokens" field.
func LifetimeCreditedTokensNEQ(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNEQ(FieldLifetimeCreditedTokens, v))
}

// LifetimeCreditedTokensIn applies the In predicate on the "lifetime_credited_tokens" field.
func LifetimeCreditedTokensIn(vs ...int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldIn(FieldLifetimeCreditedTokens, vs...))
}

// LifetimeCreditedTokensNotIn applies the NotIn predicate on the "lifetime_credited_tokens" field.
func LifetimeCreditedTokensNotIn(vs ...int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNotIn(FieldLifetimeCreditedTokens, vs...))
}

// LifetimeCreditedTokensGT applies the GT predicate on the "lifetime_credited_tokens" field.
func LifetimeCreditedTokensGT(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGT(FieldLifetimeCreditedTokens, v))
}

// LifetimeCreditedTokensGTE applies the GTE predicate on the "lifetime_credited_tokens" field.
func LifetimeCreditedTokensGTE(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGTE(FieldLifetimeCreditedTokens, v))
}

// LifetimeCreditedTokensLT applies the LT predicate on the "lifetime_credited_tokens" field.
func LifetimeCreditedTokensLT(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLT(FieldLifetimeCreditedTokens, v))
}

// LifetimeCreditedTokensLTE applies the LTE predicate on the "lifetime_credited_tokens" field.
func LifetimeCreditedTokensLTE(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLTE(FieldLifetimeCreditedTokens, v))
}

// LifetimeDebitedTokensEQ applies the EQ predicate on the "lifetime_debited_tokens" field.
func LifetimeDebitedTokensEQ(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldLifetimeDebitedTokens, v))
}

// LifetimeDebitedTokensNEQ applies the NEQ predicate on the "lifetime_debited_tokens" field.
func LifetimeDebitedTokensNEQ(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNEQ(FieldLifetimeDebitedTokens, v))
}

// LifetimeDebitedTokensIn applies the In predicate on the "lifetime_debited_tokens" field.
func LifetimeDebitedTokensIn(vs ...int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldIn(FieldLifetimeDebitedTokens, vs...))
}

// LifetimeDebitedTokensNotIn applies the NotIn predicate on the "lifetime_debited_tokens" field.
func LifetimeDebitedTokensNotIn(vs ...int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNotIn(FieldLifetimeDebitedTokens, vs...))
}

// LifetimeDebitedTokensGT applies the GT predicate on the "lifetime_debited_tokens" field.
func LifetimeDebitedTokensGT(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGT(FieldLifetimeDebitedTokens, v))
}

// LifetimeDebitedTokensGTE applies the GTE predicate on the "lifetime_debited_tokens" field.
func LifetimeDebitedTokensGTE(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGTE(FieldLifetimeDebitedTokens, v))
}

// LifetimeDebitedTokensLT applies the LT predicate on the "lifetime_debited_tokens" field.
func LifetimeDebitedTokensLT(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLT(FieldLifetimeDebitedTokens, v))
}

// LifetimeDebitedTokensLTE applies the LTE predicate on the "lifetime_debited_tokens" field.
func LifetimeDebitedTokensLTE(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLTE(FieldLifetimeDebitedTokens, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.FieldLTE(FieldVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserTokenWallet) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserTokenWallet) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserTokenWallet) predicate.UserTokenWallet {
	return predicate.UserTokenWallet(sql.NotPredicates(p))
}
